import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IconNavbar } from "@/components/navigation/top";
import { Msme } from "@/lib/types";
import { FooterNav } from "@/components/navigation/bottom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const msme: Msme = {
  address: "",
  year_established: "",
  is_active: true,
  name: "string",
  city: "string",
  working_hours: "string",
  subdomain: "string",
  state: "string",
  logo: "string",
  created_at: "string",
  country: "string",
  industry: "string",
  zip_code: null,
  services: "string",
  id: "string",
  contact_number: "string",
  ratings: 4,
  contact_email: "string",
  pricing: "string",
  description: null,
  gst: "string"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen flex-col mx-auto bg-background">
          <header className="sticky top-0 z-50 w-full py-4 px-4 sm:px-6 lg:px-8">
            <IconNavbar
              className="border-b-0"
              msme={msme}
              defaultItemId="production-orders"
            />
          </header>

          {/* Scrollable Main Content Area */}
          <main className="flex-grow overflow-y-auto">
            <div className="py-6 px-4 sm:px-6 lg:px-8"> {/* Padded container for children */}
              {children}
            </div>
          </main>
          {/* Footer Navigation */}
          <footer className="sticky bottom-0 z-50 w-full py-4 px-4 sm:px-6 lg:px-8">
            <FooterNav />
          </footer>
        </div>
      </body>
    </html>
  );
}
